dataset_folder: data/dataset
missions_csv: dataset_builder/configs/missions_build.csv
dataset_type: geo  # geo | tel
paths_per_image: 8
max_nan_frac: 0.75
min_nan_dist_cells: 10
device: cuda
seed: 42
map_size: 4.0
map_resolution: 0.04
goal_time: 5.0
goal_time_mean: 5.0
goal_time_std: 2.5

mppi:
  # Integration
  dt: 0.1
  horizon: 50

  # Optimizer
  population_size: 512
  num_iterations: 15
  gamma: 1.0
  sigma: 0.95
  beta: 0.3
  provide_zero_action: true

  # Action limits [vx, vy, wz] in m/s, m/s, rad/s
  lower_bound: [-0.2, -0.2, -0.8]
  upper_bound: [1.0, 0.2, 0.8]

  # Action filtering
  vel_lin_min: 0.2
  vel_ang_min: 0.2

  # Action cost weights
  action_cost_rotation: 1.0
  action_cost_trans_forward: 1.0
  action_cost_trans_side: 10.0

  # Traversability cost weights
  traversability_cost: 8.0
  traversability_unknown_cost: 60.0
  footprint:
    - [[-0.55, -0.26], [0.55, 0.26]]

  # Goal distance / heading costs
  position_cost: 200.0
  heading_cost: 25.0
  position_cost_at_goal_tolerance: 0.1
  heading_cost_at_goal_tolerance: 0.5
  max_distance_for_heading_cost: 2.0
  at_goal_reward: 50.0
  position_cost_mean_limit: 1000.0
  distance_pre_log_factor: 2.0

  # Traversability thresholds
  safe_th: 0.3
  risky_th: 0.8
  fatal_th: 0.9
  risky_value: 2.0
  fatal_value: 100000.0
  fatal_cells_buffer: 0
  gdf_obstacle_buffer: 1

hydra:
  run:
    dir: .
  output_subdir: null
